#!/usr/bin/python2

# diff2html
# 
# Copyright (C) 2001 Yves Bailly <diff2html@tuxfamily.org>
#           (C) 2001 MandrakeSoft S.A.
#
# This script is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This script is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA, or look at the website 
# http://www.gnu.org/copyleft/gpl.html

import sys, os, string, re, time, stat

default_css = \
"""
TABLE { border-collapse: collapse; border-spacing: 0px; }
diff-table {overflow:auto; max-height:270px; max-width: 950px; margin-top: 10px;}
.linenum a {color: #909090;}
    TD.linenum {
        text-align: right;
        vertical-align: top;
        font-weight: bold;
        border-right: 1px solid black;}
    TD.added { background-color: #a6b0d1; padding: 0px 0px 0px 15px;white-space: pre-wrap;}
    TD.modified { background-color: #c4df9b; padding: 0px 0px 0px 15px;white-space: pre-wrap;}
    TD.removed { background-color: #f9ad81; padding: 0px 0px 0px 15px;white-space: pre-wrap;}
    TD.normal {background-color: #FFFFE1;padding: 0px 0px 0px 15px;white-space: pre-wrap;}
    TD.break-line {padding: 0px 0px 0px 15px;}
    .legend { background-color: #fff799; padding: 0px 0px 0px 15px;}
    .diff-legend-header {
        border-top-left-radius: 20px;
        border-top-right-radius: 20px;
        padding: 10px 0px 0px 15px;
    }
    .legend-box {
        position:absolute;
        top:0px;
        right: 0px;
        font-size:12px;
        border-left: 1px solid #928E8E;
        border-bottom: 1px solid #928E8E;
    }
"""

def print_usage() :
    print """
diff2html - Formats diff(1) output to an HTML page on stdout
http://diff2html.tuxfamily.org

Usage: diff2html [--help] [--only-changes] [--style-sheet file.css]
                 [diff options] file1 file2

--help                  This message
--only-changes          Do not display lines that have not changed
--style-sheet file.css  Use an alternate style sheet, linked to the given file
diff options            All other options are passed to diff(1)

Example:
# Basic use
diff2html file1.txt file2.txt > differences.html
# Treat all files as text and compare  them  line-by-line, even if they do 
# not seem to be text.
diff2html -a file1 file2 > differences.html
# The same, but use the alternate style sheet contained in diff_style.css
diff2html --style-sheet diff_style.css -a file1 file2 > differences.html

The default, hard-coded style sheet is the following:%s
Note 1: if you give invalid additionnal options to diff(1), diff2html will
        silently ignore this, but the resulting HTML page will be incorrect;
Note 2: for now, diff2html can't be used with standard input, so the diff(1)
        '-' option can't be used.
        
diff2html is released under the GNU GPL.
Feel free to submit bugs or ideas to <diff2html@tuxfamily.org>.
""" % default_css

def str2html(s) :
    if ( len(s) == 0 ) : return ( s ) ;
    s1 = string.replace(s, "&", "&amp;")
    s1 = string.replace(s1, "<", "&lt;")
    s1 = string.replace(s1, ">", "&gt;")
    s1 = string.replace(s1, " ", "&nbsp;")

    return ( s1 )

def str2html2(s,s2) :
    s2temp = ""
    for i, x in enumerate(s2) :
	if ( i >= len(s) or x != s[i]) :
		s2temp += "<u>" + str2html(s2[i]) + "</u>"		
	else :
		s2temp += str2html(s2[i])

    return [str2html(s), s2temp]




if ( __name__ == "__main__" ) :

    # Processes command-line options
    cmd_line = string.join(sys.argv)
    
    # First, look for "--help"
    if ( len(sys.argv) < 3 ) :
        print_usage()
        sys.exit(1)
    for ind_opt in range(len(sys.argv)) :
        if ( sys.argv[ind_opt] == "--help" ) :
            print_usage()
            sys.exit(0)
    
    external_css = ""
    ind_css = -1
    ind_chg = -1
    only_changes = 0
    argv = tuple(sys.argv)
    for ind_opt in range(len(argv)) :
        if ( argv[ind_opt] == "--style-sheet" ) :
            ind_css = in_opt
            external_css = argv[ind_css+1]
        if ( argv[ind_opt] == "--only-changes" ) :
            ind_chg = ind_opt
            only_changes = 1

    argv = list(argv)
    if ( ind_css >= 0 ) :
        del argv[ind_css:ind_css+2]
    if ( ind_chg >= 0 ) :
        del argv[ind_chg:ind_chg+1]

    # Check if both files exists
    file1 = argv[-2]
    file2 = argv[-1]
    if not os.access(file1, os.F_OK) :
        print "File %s does not exist or is not readable, aborting." % file1
        sys.exit(1)
    if not os.access(file2, os.F_OK) :
        print "File %s does not exist or is not readable, aborting." % file2
        sys.exit(1)

    # Invokes "diff"
    diff_stdout = os.popen("diff %s --text" % string.join(argv[1:]), "r")
    diff_output = diff_stdout.readlines()
    diff_stdout.close()
    # Maps to store the reported differences
    changed = {}
    deleted = {}
    added = {}
    # Magic regular expression
    diff_re = re.compile(
        r"^(?P<f1_start>\d+)(,(?P<f1_end>\d+))?"+ \
         "(?P<diff>[acd])"+ \
         "(?P<f2_start>\d+)(,(?P<f2_end>\d+))?")
    # Now parse the output from "diff"
    for diff_line in diff_output:
        diffs = diff_re.match(string.strip(diff_line))
        # If the line doesn't match, it's useless for us
        if not ( diffs  == None ) :
            # Retrieving informations about the differences : 
            # starting and ending lines (may be the same)
            f1_start = int(diffs.group("f1_start"))
            if ( diffs.group("f1_end") == None ) :
                f1_end = f1_start
            else :
                f1_end = int(diffs.group("f1_end"))
            f2_start = int(diffs.group("f2_start"))
            if ( diffs.group("f2_end") == None ) :
                f2_end = f2_start
            else :
                f2_end = int(diffs.group("f2_end"))
            f1_nb = (f1_end - f1_start) + 1
            f2_nb = (f2_end - f2_start) + 1
            # Is it a changed (modified) line ?
            if ( diffs.group("diff") == "c" ) :
                # We have to handle the way "diff" reports lines merged
                # or splitted
                if ( f2_nb < f1_nb ) :
                    # Lines merged : missing lines are marqued "deleted"
                    for lf1 in range(f1_start, f1_start+f2_nb) :
                        changed[lf1] = 0
                    for lf1 in range(f1_start+f2_nb, f1_end+1) :
                        deleted[lf1] = 0
                elif ( f1_nb < f2_nb ) :
                    # Lines splitted : extra lines are marqued "added"
                    for lf1 in range(f1_start, f1_end+1) :
                        changed[lf1] = 0
                    for lf2 in range(f2_start+f1_nb, f2_end+1) :
                        added[lf2] = 0
                else :
                    # Lines simply modified !
                    for lf1 in range(f1_start, f1_end+1) :
                        changed[lf1] = 0
            # Is it an added line ?
            elif ( diffs.group("diff") == "a" ) :
                for lf2 in range(f2_start, f2_end+1):
                    added[lf2] = 0
            else :
            # OK, so it's a deleted line
                for lf1 in range(f1_start, f1_end+1) :
                    deleted[lf1] = 0

    # Storing the two compared files, to produce the HTML output
    f1 = open(file1, "r")
    f1_lines = f1.readlines()
    f1.close()
    f2 = open(file2, "r")
    f2_lines = f2.readlines()
    f2.close()
    
    # Finding some infos about the files
    f1_stat = os.stat(file1)
    f2_stat = os.stat(file2)

    # Printing the HTML header, and various known informations
    

    print """
<div>
	<div class="diff-table">
	<table id="legend-table">
    		<tbody>
			<tr>
				<th>&nbsp;</th>
				<th width="45%" class="diff-legend-header legend"><strong><big>Resposta Esperada</big></strong></th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th width="45%" class="diff-legend-header legend"><strong><big>Resposta Obtida</big></strong></th>
			</tr>
		</tbody>
""" 
    # Running through the differences...
    nl1 = nl2 = 0
    while not ( (nl1 >= len(f1_lines)) and (nl2 >= len(f2_lines)) ) :
	line1 = ""
	if (nl1 < len(f1_lines) and nl2 < len(f2_lines)) :
	    htmlStr = str2html2(f1_lines[nl1],f2_lines[nl2])
	elif (nl1 < len(f1_lines)) :
	    htmlStr = str2html2(f1_lines[nl1],"")
	elif (nl2 < len(f2_lines)) :
	    htmlStr = str2html2("",f2_lines[nl2])
	if (nl2 < len(f2_lines) - 1) :
	    htmlStr[1] = string.replace(htmlStr[1], "<u>\n</u>","&#9166")
	    htmlStr[1] = string.replace(htmlStr[1], "\n","&#9166")
	if (nl1 < len(f1_lines) - 1) :
	    htmlStr[0] = string.replace(htmlStr[0], "\n","&#9166")
        if ( added.has_key(nl2+1) ) :
            htmlStr[1]
      # This is an added line
            print """
    <tr>
        <td class="linenum">&nbsp;</td>
        <td class="added">&nbsp;</td>
        <td width="16">&nbsp;</td>
        <td class="linenum"><a name="F2_%d">%d</a></td>
        <td class="added">%s</td>
    </tr>
""" % (nl2+1, nl2+1, htmlStr[1])	    
            nl2 += 1
        elif ( deleted.has_key(nl1+1) ) :
      # This is a deleted line
            print """
    <tr>
        <td class="linenum"><a name="F1_%d">%d</a></td>
        <td class="removed">%s</td>
        <td width="16">&nbsp;</td>
        <td class="linenum">&nbsp;</td>
        <td class="removed">&nbsp;</td>
    </tr>
""" % (nl1+1, nl1+1, htmlStr[0])
            nl1 += 1
        elif ( changed.has_key(nl1+1) ) :
      # This is a changed (modified) line
            print """
    <tr>
        <td class="linenum"><a name="F1_%d">%d</a></td>
        <td class="modified">%s</td>
        <td width="16">&nbsp;</td>
        <td class="linenum">%d</td>
        <td class="modified">%s</td>
    </tr>
""" % (nl1+1, nl1+1, htmlStr[0], 
       nl2+1, htmlStr[1])
            nl1 += 1
            nl2 += 1
        else :
      # These lines have nothing special
            if ( not only_changes ) :
                print """
    <tr>
        <td class="linenum">%d</td>
        <td class="normal">%s</td>
        <td width="16">&nbsp;</td>
        <td class="linenum">%d</td>
        <td class="normal">%s</td>
    </tr>
""" % (nl1+1, htmlStr[0],
       nl2+1, htmlStr[1])
            nl1 += 1
            nl2 += 1
            
    # And finally, the end of the HTML
    print """
        </table>               
    </div>               
</div>
"""
#<div class="legend-box">
#	<table>
#		<tbody id="diff-legend">
#			<tr><td class="legend">Legenda</td></tr>
#			<tr><td class="normal">Correto</td></tr>
#			<tr><td class="modified">Errado</td></tr>
#			<tr><td class="break-line">Quebra de linha: &#9166</td></tr>
#		</tbody>
#	</table>
#</div>
#       </div>
#
#"""
